spring:
  datasource :
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    properties:
      hibernate:
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

#spring.jpa.properties.hibernate.show_sql=true
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-ocnsole
